name: Build Qt 5.12.12 Static (VS2022)

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  build-qt-static:
    runs-on: windows-2022  # 使用预装 VS2022 的 GitHub 运行器

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装 Chocolatey 包管理器
    - name: Install Chocolatey
      shell: powershell
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    # 安装编译依赖
    - name: Install Dependencies
      shell: powershell
      run: |
        choco install -y --no-progress strawberryperl
        choco install -y --no-progress python
        refreshenv

    # 配置 VS2022 开发环境
    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64  # 支持 x86/x64/ARM64

    # 缓存 Qt 源码（减少重复下载）
    - name: Cache Qt Source
      uses: actions/cache@v3
      id: cache-qt
      with:
        path: |
          qt-src/
          qt-everywhere-src-5.12.12.tar.xz
        key: ${{ runner.os }}-qt-5.12.12-source

    # 下载并解压 Qt 源码
    - name: Download Qt Source
      if: steps.cache-qt.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        curl -L -o qt-everywhere-src-5.12.12.tar.xz https://download.qt.io/archive/qt/5.12/5.12.12/single/qt-everywhere-src-5.12.12.tar.xz
        7z x qt-everywhere-src-5.12.12.tar.xz
        7z x qt-everywhere-src-5.12.12.tar
        ren qt-everywhere-src-5.12.12 qt-src

    # 配置静态编译参数
    - name: Configure Qt
      shell: cmd
      run: |
        cd qt-src
        configure.bat -static -release -opensource -confirm-license ^
          -prefix "C:\Qt\5.12.12-static-msvc2022" ^
          -platform win32-msvc ^
          -nomake examples -nomake tests ^
          -qt-zlib -qt-libpng -qt-libjpeg ^
          -opengl desktop -mp ^
          -skip webengine -skip qtwebengine -skip qtwebview

    # 编译 Qt（使用 jom 加速）
    - name: Build Qt
      shell: cmd
      run: |
        cd qt-src
        jom -j %NUMBER_OF_PROCESSORS%
        jom install

    # 打包并上传产物
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Qt5.12.12-Static-VS2022
        path: C:\Qt\5.12.12-static-msvc2022
        retention-days: 7
