name: Build Qt 5.12.12 Static

on:
  workflow_dispatch:  
  push:
    branches: [ main ]

jobs:
  build-qt-static:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-latest ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Install Dependencies
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev libxkbcommon-dev libfontconfig1-dev libdbus-1-dev libssl-dev
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          choco install -y python --version 3.9.13
          choco install -y strawberryperl --version 5.32.1.1
          refreshenv
        fi

    - name: Download Qt 5.12.12 Source
      run: |
        wget https://download.qt.io/archive/qt/5.12/5.12.12/single/qt-everywhere-src-5.12.12.tar.xz
        tar -xf qt-everywhere-src-5.12.12.tar.xz
        mv qt-everywhere-src-5.12.12 qt-src


    - name: Configure Qt Static Build
      shell: bash
      run: |
        cd qt-src
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          ./configure -prefix /opt/qt5.12.12-static \
            -static -release -opensource -confirm-license \
            -nomake examples -nomake tests \
            -qt-zlib -qt-libpng -qt-libjpeg -qt-xcb
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          ./configure -prefix C:\qt5.12.12-static ^
            -static -release -opensource -confirm-license ^
            -nomake examples -nomake tests ^
            -qt-zlib -qt-libpng -qt-libjpeg -opengl desktop
        fi


    - name: Build and Install
      shell: bash
      run: |
        cd qt-src
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          make -j$(nproc)
          sudo make install
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          jom.exe -j $NUMBER_OF_PROCESSORS
          jom.exe install
        fi


    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: qt5.12.12-static-${{ runner.os }}
        path: |
          ${{ runner.os == 'Linux' && '/opt/qt5.12.12-static' || 'C:\qt5.12.12-static' }}
